= enV5.2 Hardware Tests
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[.lead]
This project aims to provide simple implementations to test newly produced/delivered enV5 hardware.

toc::[]

== Setup

For compiling the project, the required tools are:

.Prerequisites
- gcc (local C compiler)
- arm-non-eabi-gcc (C compiler for RP2040)
- CMake (Build Script Generator)
- Ninja (Build Tool)

.Local Setup
. Install all required tools (see Prerequisites)
. Clone the repo to your local machine
. Open the project in your preferred C/C++ IDE

NOTE: If you use the CLion IDE as recommended, the build script generation is done by the IDE itself.
If you want to do this by yourself, please refer to <<CMake>>.

[IMPORTANT]
====
You have to adjust the network/mqtt broker credentials as mentioned in the link:https://github.com/es-ude/elastic-ai.runtime.enV5/blob/d862d803a56f0371f9a027b0f304b9ddfa7cd541/src/network/README.adoc[network README]!
====

[#_cmake]
== CMake

There are three CMake Profiles provided with the CLion settings:
*Debug*, *Release*, and *UnitTests*.

Only the _UnitTests_ profile allows you to compile source code for your local machine and therefore run the unit tests.
The _Debug_ and _Release_ targets differ only in the amount of printed information when the software is executed on an enV5-device.

.Profiles
[source,bash]
----
# Debug profile
cmake -B build/debug -G Ninja -D CMAKE_BUILD_TYPE=DEBUG -D DEBUG_MODE:BOOL=ON

# Release profile
cmake -B build/release -G Ninja -D CMAKE_BUILD_TYPE=RELEASE -D DEBUG_MODE:BOOL=OFF
----

The flag `-G Ninja` tells CMake to use Ninja as the build tool.
If this flag is not passed, CMake will use the default build tool on your machine (mostly Makefiles).

[#_target_pico]
=== Target Pico

[#_build_all_targets]
==== Build all Targets

The debug targets can be built by executing:

[source,bash]
----
cmake --build build/debug -j 4
----

The release targets can be built by executing:

[source,bash]
----
cmake --build build/release -j 4
----

The `*.uf2` files to flash the pico can than be found under the
link:out[out] folder.

[#_hardware_tests]
==== Hardware Tests

The hardware tests can be build using

[source,bash]
----
cmake --build build/debug -j 4 --target <test_name>
----

replacing `<test_name>` with the name of the test.

The resulting `<test_name>.u2f` files to flash the pico can be found under the link:./out[out] folder.

[#_flashing_the_elastic_node_version_5_env5]
==== Flashing the Elastic Node version 5 (enV5)

. Press and hold `MCU BOOT` on the Elastic Node
. Press `MCU RST` on the Elastic Node
. Release `MCU BOOT`
. Copy the `*.uf2` File to the RPI-RP2 device

[#_cmd_line_output]
==== CMD line output

If the pico is connected to the local machine the `printf()` statements inside the code will be redirected to the USB and are available as serial port output.
This output can be read via a serial port reader like screen, minicom or https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html[putty].

The following example shows how to use minicom on a Unix-based system:

[source,bash]
----
minicom \
-b 115200  \ #<1>
-o \ #<2>
-D /dev/ttyACM0 #<3>
----

<1> `-b 115200` -> baud rate for connection
<2> `-o` -> disable modem initialisation
<3> `-D /dev/ttyACM0` -> serial port

[IMPORTANT]
====
The serial port differs depending on the host machine!
It can be found via `ls /dev/tty*` (Linux) or `ls /dev/tty.*` (macOS) from the terminal.
====

[#_debug_output]
==== Debug Output

To enable enhanced Debug output, add the flag `-D DEBUG_OUTPUT:BOOL=ON`
to the <<_cmake,CMake Setup call>> (or add it in the CLion CMake options).
This enables the `PRINT_DEBUG(...)` from the common_lib of the enV5 repository in all targets.

=== Clion specific settings

Clion automatically detects targets and adds them to the configurations in the upper right corner.
These can be built via one of the profiles.
There are three profiles in total:

* `Debug`: build targets for the RP2040 with debug logs
* `Release`: build targets for the RP2040 without debug logs

== Project structure

This project contains various folders:

[cols=">,<",options="header"]
|===
|Folder |Description

|link:build[]
|contains all CMake generated build scripts and resources

|link:out[]
|contains all executables (`*.uf2` binary files) for the enV5

|link:src[]
|contains helpers and hardware test implementations
|===

== Further Reading

* link:https://github.com/es-ude/elastic-ai.runtime.enV5/blob/d862d803a56f0371f9a027b0f304b9ddfa7cd541/README.adoc[enV5 README]
* link:https://github.com/es-ude/elastic-ai.runtime.enV5/blob/d862d803a56f0371f9a027b0f304b9ddfa7cd541/documentation/SETUP_GUIDE.adoc[enV5 Setup Guide]